name: Update dependencies packages

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create new branch
        run: hub checkout -b dependencies-update-${{ steps.date.outputs.date }}

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn package

      - name: Update dependencies
        id: update-dependencies
        run: |
          DEPENDENCY=`mvn versions:display-dependency-updates`
          echo A
          echo $DEPENDENCY
          echo B
          ESCAPED_DEPENDENCY="${$DEPENDENCY//$'\n'/\\n}"
          echo C
          echo $ESCAPED_DEPENDENCY
          echo D
          echo "::set-output name=dependency::$ESCAPED_DEPENDENCY"
          echo E
          echo -e $DEPENDENCY > dependencies-update.txt
          echo F
          mvn versions:use-next-releases

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Is modified
        id: is-modified
        run: |
          git status | grep modified
          echo "::set-output name=modified::`echo $?`"

      - name: Create pull request
        if: ${{ steps.is-modified.outputs.modified == '0' }}
        run: |
          hub add -A
          hub commit -m "chore: Update dependencies packages"
          hub push --set-upstream origin dependencies-update-${{ steps.date.outputs.date }}
          echo "\`\`\`\n${{ steps.update-dependencies.outputs.dependency }}\n\`\`\`" > description.md
          hub pull-request -b master -m "Update dependencies packages" -r book000 -F description.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
